CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_normalized CHECK (email = lower(btrim(email)))
);

-- Existing URLs remain public but cannot be claimed or managed by any account.
ALTER TABLE short_urls ADD COLUMN user_id BIGINT REFERENCES users(id);
CREATE INDEX ix_short_urls_user_id_id ON short_urls (user_id, id DESC);
