CREATE TABLE click_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url_id BIGINT NOT NULL REFERENCES short_urls(id) ON DELETE CASCADE,
    accessed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    referrer VARCHAR(253) NOT NULL,
    device VARCHAR(16) NOT NULL,
    geography VARCHAR(64) NOT NULL
);

CREATE INDEX ix_click_events_url_time ON click_events (short_url_id, accessed_at);
CREATE INDEX ix_short_urls_active_expiry ON short_urls (expires_at, id)
    WHERE active = TRUE AND expires_at IS NOT NULL;
